workflows:
  rust-build:
    name: Rust Build
    instance_type: mac_mini_m1 # or another suitable instance type
    scripts:
      - name: Install Rust
        script: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          pwd
          cargo install uniffi-bindgen-go --git https://github.com/NordSecurity/uniffi-bindgen-go --tag v0.2.1+v0.25.0
          uniffi-bindgen-go src/ldk_node.udl -o ffi/golang -c ./uniffi.toml
          cargo build --release
          cp ./target/release/libldk_node_bindings.dylib ffi/golang/ldk_node
    artifacts:
      - ffi/golang/ldk_node/*
