workflows:
  rust-build:
    name: Rust Build
    instance_type: mac_mini_m1 # or another suitable instance type
    scripts:
      - name: Install Rust
        script: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
      - name: Build Rust Project
        script: |
          cargo install uniffi-bindgen-go --git https://github.com/NordSecurity/uniffi-bindgen-go --tag v0.2.1+v0.25.0
          /clone/scripts/uniffi_bindgen_generate_go.sh
          cp ./target/release/libldk_node_bindings.dylib ffi/golang/ldk_node
    artifacts:
      - clone/ffi/golang/ldk_node/*
